apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: next-test
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: next-test
    spec:
      containers:
      - name: next-test
        image: 301647596003.dkr.ecr.us-east-1.amazonaws.com/next-test:latest
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
        ports:
        - containerPort: 3000